Traceback (most recent call last):
  File "/Users/tyler/.mambaforge/envs/nlp_workshop/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/tyler/.mambaforge/envs/nlp_workshop/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tyler/.mambaforge/envs/nlp_workshop/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tyler/.mambaforge/envs/nlp_workshop/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/tyler/.mambaforge/envs/nlp_workshop/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/tyler/.mambaforge/envs/nlp_workshop/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/tyler/.mambaforge/envs/nlp_workshop/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
topic_terms = np.stack([tuned.get_topic_word_dist(k) for k in range(tuned.k)])
doc_lengths = np.array([len(doc.words) for doc in tuned.docs])
vocab = list(tuned.used_vocabs)
term_frequency = tuned.used_vocab_freq

vis = pyLDAvis.prepare(
    topic_terms, theta.values, doc_lengths, vocab, term_frequency
    , start_index = 0, sort_topics = False
)
pyLDAvis.save_html(vis, indir.joinpath("output/topic_model_plot.html"))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[47], line 10[0m
[1;32m      4[0m term_frequency [38;5;241m=[39m tuned[38;5;241m.[39mused_vocab_freq
[1;32m      6[0m vis [38;5;241m=[39m pyLDAvis[38;5;241m.[39mprepare(
[1;32m      7[0m     topic_terms, theta[38;5;241m.[39mvalues, doc_lengths, vocab, term_frequency
[1;32m      8[0m     , start_index [38;5;241m=[39m [38;5;241m0[39m, sort_topics [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m      9[0m )
[0;32m---> 10[0m [43mpyLDAvis[49m[38;5;241;43m.[39;49m[43msave_html[49m[43m([49m[43mvis[49m[43m,[49m[43m [49m[43mindir[49m[38;5;241;43m.[39;49m[43mjoinpath[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43moutput/topic_model_plot.html[39;49m[38;5;124;43m"[39;49m[43m)[49m[43m)[49m

File [0;32m~/.mambaforge/envs/nlp_workshop/lib/python3.11/site-packages/pyLDAvis/_display.py:356[0m, in [0;36msave_html[0;34m(data, fileobj, **kwargs)[0m
[1;32m    354[0m         fileobj [38;5;241m=[39m [38;5;28mopen[39m(fileobj, [38;5;124m'[39m[38;5;124mw[39m[38;5;124m'[39m)
[1;32m    355[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mhasattr[39m(fileobj, [38;5;124m'[39m[38;5;124mwrite[39m[38;5;124m'[39m):
[0;32m--> 356[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mfileobj should be a filename or a writable file[39m[38;5;124m"[39m)
[1;32m    357[0m fileobj[38;5;241m.[39mwrite(prepared_data_to_html(data, [38;5;241m*[39m[38;5;241m*[39mkwargs))

[0;31mValueError[0m: fileobj should be a filename or a writable file

